# Generated by Django 4.1.3 on 2022-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuser',
            fields=[
                ('nuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
                ('point', models.IntegerField()),
            ],
            options={
                'db_table': 'netshop_nusers',
            },
        ),
    ]
