# Generated by Django 4.1.3 on 2022-11-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
