# Generated by Django 4.1.3 on 2022-11-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('nusers', '0001_initial'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery')),
                ('nuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nusers.nuser')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'netshop_orders',
            },
        ),
    ]
